# Generated by Django 5.2.5 on 2025-08-31 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('problems', models.ManyToManyField(related_name='pledged_in_goals', to='core.problem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='core.profile')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('profile', 'start_date')},
            },
        ),
    ]
